/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.down;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Cleber
 */
public class NewDownloadPanel extends javax.swing.JPanel {
    FrmPrincipal frame;
    /**
     * Creates new form NewDownloadPanel
     */
    public NewDownloadPanel(FrmPrincipal frame) {
        initComponents();
        this.frame = frame;
    }
    
    public void reset(){
            txtURL.setText("Insira a URL do download..");
            txtURL.setForeground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtURL = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(32767, 71));
        setPreferredSize(new java.awt.Dimension(569, 91));

        txtURL.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtURL.setForeground(new java.awt.Color(153, 153, 153));
        txtURL.setText("Insira a URL do download..");
        txtURL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtURL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtURLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtURLFocusLost(evt);
            }
        });
        txtURL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtURLPropertyChange(evt);
            }
        });
        txtURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtURLKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtURLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtURLFocusGained
        if(txtURL.getText().equals("Insira a URL do download..")){
           txtURL.setText("");
           txtURL.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtURLFocusGained

    private void txtURLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtURLFocusLost
        if(txtURL.getText().equals("")){
            reset();
        }
    }//GEN-LAST:event_txtURLFocusLost

    private void txtURLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtURLKeyPressed
        if(evt.getKeyCode()==10){
            try {
                if(frame.addDownload(txtURL.getText())){
                    this.setVisible(false);
                }
                reset();
            } catch (Exception ex) {
                Logger.getLogger(NewDownloadPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(evt.getKeyCode()==27){
            this.setVisible(false);
            reset();
        }
        
    }//GEN-LAST:event_txtURLKeyPressed

    private void txtURLPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtURLPropertyChange

    }//GEN-LAST:event_txtURLPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
